[2024-03-18T08:04:35.177+0000] {processor.py:161} INFO - Started process (PID=5093) to work on /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:04:35.178+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dag.py for tasks to queue
[2024-03-18T08:04:35.179+0000] {logging_mixin.py:188} INFO - [2024-03-18T08:04:35.179+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:04:35.484+0000] {logging_mixin.py:188} INFO - [2024-03-18T08:04:35.482+0000] {dagbag.py:350} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/air_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dag.py", line 92, in <module>
    transform_load_weather_data = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-03-18T08:04:35.485+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:04:35.505+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dag.py took 0.331 seconds
[2024-03-18T08:05:16.400+0000] {processor.py:161} INFO - Started process (PID=5431) to work on /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:05:16.401+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dag.py for tasks to queue
[2024-03-18T08:05:16.402+0000] {logging_mixin.py:188} INFO - [2024-03-18T08:05:16.402+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:05:16.839+0000] {logging_mixin.py:188} INFO - [2024-03-18T08:05:16.838+0000] {dagbag.py:350} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/air_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dag.py", line 92, in <module>
    transform_load_weather_data = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-03-18T08:05:16.840+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:05:16.862+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dag.py took 0.466 seconds
[2024-03-18T08:06:03.016+0000] {processor.py:161} INFO - Started process (PID=5959) to work on /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:06:03.063+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dag.py for tasks to queue
[2024-03-18T08:06:03.064+0000] {logging_mixin.py:188} INFO - [2024-03-18T08:06:03.064+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:06:04.457+0000] {logging_mixin.py:188} INFO - [2024-03-18T08:06:04.456+0000] {dagbag.py:350} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/air_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dag.py", line 92, in <module>
    transform_load_weather_data = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-03-18T08:06:04.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:06:04.488+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dag.py took 1.691 seconds
[2024-03-18T08:06:54.924+0000] {processor.py:161} INFO - Started process (PID=6675) to work on /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:06:54.926+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dag.py for tasks to queue
[2024-03-18T08:06:54.927+0000] {logging_mixin.py:188} INFO - [2024-03-18T08:06:54.926+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:06:55.233+0000] {logging_mixin.py:188} INFO - [2024-03-18T08:06:55.232+0000] {dagbag.py:350} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/air_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dag.py", line 92, in <module>
    transform_load_weather_data = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-03-18T08:06:55.233+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:06:55.254+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dag.py took 0.333 seconds
[2024-03-18T08:07:43.429+0000] {processor.py:161} INFO - Started process (PID=7166) to work on /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:07:43.431+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dag.py for tasks to queue
[2024-03-18T08:07:43.432+0000] {logging_mixin.py:188} INFO - [2024-03-18T08:07:43.432+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:07:43.742+0000] {logging_mixin.py:188} INFO - [2024-03-18T08:07:43.741+0000] {dagbag.py:350} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/air_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dag.py", line 92, in <module>
    transform_load_weather_data = PythonOperator(
NameError: name 'PythonOperator' is not defined
[2024-03-18T08:07:43.743+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:07:43.762+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dag.py took 0.336 seconds
[2024-03-18T08:08:29.467+0000] {processor.py:161} INFO - Started process (PID=7307) to work on /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:08:29.469+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dag.py for tasks to queue
[2024-03-18T08:08:29.470+0000] {logging_mixin.py:188} INFO - [2024-03-18T08:08:29.469+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:08:29.768+0000] {logging_mixin.py:188} INFO - [2024-03-18T08:08:29.766+0000] {dagbag.py:350} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dag.py
Traceback (most recent call last):
  File "/home/ubuntu/air_venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dag.py", line 8, in <module>
    from airflow.providers.python.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.python'
[2024-03-18T08:08:29.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dag.py
[2024-03-18T08:08:29.804+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dag.py took 0.342 seconds
